# Generated by Django 4.2.16 on 2025-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparcelle',
            name='enquete_uid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name="Identifiant de l'enquete "),
        ),
        migrations.AlterField(
            model_name='historicalproducteur',
            name='enquete_uid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name="Identifiant de l'enquete "),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='enquete_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Identifiant de l'enquete "),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='enquete_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Identifiant de l'enquete "),
        ),
    ]
