# Generated by Django 4.2.16 on 2024-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='majoration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='majoration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
