# Generated by Django 4.2.16 on 2025-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=300, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=300, null=True),
        ),
    ]
