# Generated by Django 4.2.16 on 2024-12-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='nom_culture',
            field=models.CharField(choices=[('vivriere', 'Culture Vivrière'), ('industrial', 'Culture Industrielle'), ('rente', 'Culture de Rente'), ('maraichere', 'Culture Maraîchère'), ('fruitiere', 'Culture Fruitière'), ('specialisee', 'Culture Spécialisée'), ('florale', 'Culture Florale et Ornementale'), ('emergente', 'Culture Émergente')], max_length=200, verbose_name='Nom de la Culture'),
        ),
    ]
