# Generated by Django 4.2.16 on 2025-01-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='annee_cultures_precedentes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année des cultures précédentes'),
        ),
    ]
