# Generated by Django 4.2.16 on 2024-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0002_alter_mobiledata_nom_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledata',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
