# Generated by Django 4.2.16 on 2025-01-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0002_alter_mobiledata_annee_cultures_precedentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='annee_cultures_precedentes',
            field=models.CharField(blank=True, null=True, verbose_name='Année des cultures précédentes'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='annee_mise_en_place',
            field=models.PositiveIntegerField(blank=True, max_length=200, null=True, verbose_name='Année de mise en place'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='cultures_precedentes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cultures précédentes'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='type_fertilisants',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type de fertilisants'),
        ),
    ]
