# Generated by Django 4.2.16 on 2025-02-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0002_alter_mobiledata_latitude_alter_mobiledata_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiledata',
            old_name='date_recolte',
            new_name='annee_premiere_recole',
        ),
        migrations.RenameField(
            model_name='mobiledata',
            old_name='type_fertilisants',
            new_name='fertilizerType',
        ),
        migrations.RenameField(
            model_name='mobiledata',
            old_name='nombre_dependants',
            new_name='nbre_personne_charge',
        ),
        migrations.RenameField(
            model_name='mobiledata',
            old_name='taille_du_foyer',
            new_name='nbre_personne_foyer',
        ),
        migrations.RemoveField(
            model_name='mobiledata',
            name='dernier_rendement_kg_ha',
        ),
        migrations.RemoveField(
            model_name='mobiledata',
            name='pratiques_culturales',
        ),
        migrations.RemoveField(
            model_name='mobiledata',
            name='type_culture',
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='Culture_intercalaire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Culture Intercalaire '),
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='createdDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='cultureType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de Culture'),
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='handicap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='rendement_approximatif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rendement approximatif '),
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='revenue_derniere_recolte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de dépendants'),
        ),
        migrations.AddField(
            model_name='mobiledata',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='autre_culture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='autre_culture_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='evenements_climatiques',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='nom_culture',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la Culture'),
        ),
    ]
