# Generated by Django 4.2.16 on 2025-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0002_alter_historicalparcelle_enquete_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='uid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
