# Generated by Django 4.2.16 on 2024-11-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0002_employee_majoration_historicalemployee_majoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='majoration',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='majoration',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='salary',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
