# Generated by Django 4.2.16 on 2024-12-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0003_mobiledata_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='annee_mise_en_place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de mise en place'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='autre_culture',
            field=models.CharField(blank=True, choices=[('perennial', 'Culture Pérenne'), ('seasonal', 'Culture Saisonnière')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='autre_culture_nom',
            field=models.CharField(blank=True, choices=[('vivriere', 'Culture Vivrière'), ('industrial', 'Culture Industrielle'), ('rente', 'Culture de Rente'), ('maraichere', 'Culture Maraîchère'), ('fruitiere', 'Culture Fruitière'), ('specialisee', 'Culture Spécialisée'), ('florale', 'Culture Florale et Ornementale'), ('emergente', 'Culture Émergente')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='category',
            field=models.CharField(blank=True, choices=[('vivriere', 'Culture Vivrière'), ('industrial', 'Culture Industrielle'), ('rente', 'Culture de Rente'), ('maraichere', 'Culture Maraîchère'), ('fruitiere', 'Culture Fruitière'), ('specialisee', 'Culture Spécialisée'), ('florale', 'Culture Florale et Ornementale'), ('emergente', 'Culture Émergente')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localite_producteur', to='tracelan.ville'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='nom_cooperative',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='nom_culture',
            field=models.CharField(blank=True, choices=[('vivriere', 'Culture Vivrière'), ('industrial', 'Culture Industrielle'), ('rente', 'Culture de Rente'), ('maraichere', 'Culture Maraîchère'), ('fruitiere', 'Culture Fruitière'), ('specialisee', 'Culture Spécialisée'), ('florale', 'Culture Florale et Ornementale'), ('emergente', 'Culture Émergente')], max_length=200, null=True, verbose_name='Nom de la Culture'),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='type_culture',
            field=models.CharField(blank=True, choices=[('perennial', 'Culture Pérenne'), ('seasonal', 'Culture Saisonnière')], max_length=50, null=True, verbose_name='Type de Culture'),
        ),
    ]
