# Generated by Django 4.2.16 on 2025-01-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0003_alter_mobiledata_annee_cultures_precedentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='pratiques_culturales',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pratiques culturales'),
        ),
    ]
