# Generated by Django 4.2.16 on 2024-11-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0003_alter_employee_majoration_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='budget_estimatif',
            field=models.IntegerField(default=400000, verbose_name='Budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='budget_estimatif',
            field=models.IntegerField(default=300000, verbose_name='Budget'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('matériel', 'Matériel'), ('salaires', 'Salaires'), ('frais_generaux', 'Frais généraux'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='tracelan.project')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracelan.employee')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
