# Generated by Django 4.2.16 on 2025-01-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0004_alter_mobiledata_pratiques_culturales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='pratiques_culturales',
            field=models.CharField(blank=True, choices=[('agroforestry', 'Agroforesterie'), ('intercropping', 'Intercropping'), ('composting', 'Compostage')], max_length=100, null=True, verbose_name='Pratiques culturales'),
        ),
    ]
