# Generated by Django 4.2.16 on 2024-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0004_historicalproject_budget_estimatif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='majoration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='majoration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
