# Generated by Django 4.2.16 on 2024-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0004_alter_mobiledata_annee_mise_en_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='autre_culture_volume_ha',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
