# Generated by Django 4.2.16 on 2024-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0005_alter_employee_majoration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='budget_estimatif',
            field=models.IntegerField(verbose_name='Budget Estimatif'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_estimatif',
            field=models.IntegerField(verbose_name='Budget Estimatif'),
        ),
    ]
