# Generated by Django 4.2.16 on 2025-01-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0005_alter_mobiledata_pratiques_culturales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='pratiques_culturales',
            field=models.CharField(blank=True, choices=[('agroforestry', 'Agroforesterie'), ('intercropping', 'Intercropping'), ('composting', 'Compostage'), ('crop_rotation', 'Rotation des cultures'), ('mulching', 'Paillage'), ('cover_cropping', 'Culture de couverture'), ('conservation_tillage', 'Labour de conservation'), ('organic_farming', 'Agriculture biologique'), ('precision_farming', 'Agriculture de précision'), ('irrigation_management', 'Gestion de l’irrigation'), ('pest_management', 'Gestion des ravageurs'), ('fertilizer_management', 'Gestion des fertilisants'), ('soil_testing', 'Analyse du sol'), ('drip_irrigation', 'Irrigation goutte à goutte'), ('no_tillage', 'Sans labour'), ('mixed_cropping', 'Culture mixte'), ('integrated_farming', 'Agriculture intégrée'), ('green_manuring', 'Engrais verts'), ('companion_planting', 'Plantes compagnes'), ('agroecology', 'Agroécologie'), ('permaculture', 'Permaculture'), ('biocontrol', 'Biocontrôle'), ('hydroponics', 'Hydroponie'), ('aquaponics', 'Aquaponie')], max_length=100, null=True, verbose_name='Pratiques culturales'),
        ),
    ]
