# Generated by Django 4.2.16 on 2024-11-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0006_alter_historicalproject_budget_estimatif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='previsionnel',
            field=models.IntegerField(default=600000, verbose_name='Budget Previsionnel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='previsionnel',
            field=models.IntegerField(default=600000000, verbose_name='Budget Previsionnel'),
            preserve_default=False,
        ),
    ]
