# Generated by Django 4.2.16 on 2025-01-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0006_alter_mobiledata_pratiques_culturales'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducteur',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
