# Generated by Django 4.2.16 on 2024-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0007_historicalproject_previsionnel_project_previsionnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='budget_estimatif',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_estimatif',
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
