# Generated by Django 4.2.16 on 2025-01-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0007_historicalproducteur_fonction_producteur_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledata',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedby', to='tracelan.employee'),
        ),
    ]
