# Generated by Django 4.2.16 on 2025-01-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0008_mobiledata_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledata',
            name='validate_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validateby', to='tracelan.employee'),
        ),
    ]
