# Generated by Django 4.2.16 on 2024-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0009_alter_historicaltask_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='nbr_heure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heure'),
        ),
        migrations.AddField(
            model_name='task',
            name='nbr_heure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heure'),
        ),
    ]
