# Generated by Django 4.2.16 on 2025-01-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0009_mobiledata_validate_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='annee_mise_en_place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de mise en place'),
        ),
    ]
