# Generated by Django 4.2.16 on 2024-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0010_historicaltask_nbr_heure_task_nbr_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
