# Generated by Django 4.2.16 on 2024-11-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0011_alter_historicaltask_due_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracelan.employee', verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='tracelan.employee', verbose_name='Assigned To'),
        ),
    ]
