# Generated by Django 4.2.16 on 2024-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0012_alter_historicaltask_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='nbr_heure',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'Heure"),
        ),
        migrations.AlterField(
            model_name='task',
            name='nbr_heure',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'Heure"),
        ),
    ]
