# Generated by Django 4.2.16 on 2024-11-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0013_alter_historicaltask_nbr_heure_alter_task_nbr_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='previsionnel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Budget Previsionnel'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracelan.employee', verbose_name='Assigner à'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la Tâche'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, null=True, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracelan.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='previsionnel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Budget Previsionnel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='tracelan.employee', verbose_name='Assigner à'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la Tâche'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, null=True, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracelan.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
