# Generated by Django 4.2.16 on 2024-11-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0014_alter_historicalproject_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracelan.employee', verbose_name='Assigner par'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigneur', to='tracelan.employee', verbose_name='Assigner par'),
        ),
    ]
