# Generated by Django 4.2.16 on 2024-11-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0015_historicaltask_assigned_by_task_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_by', to='tracelan.employee', verbose_name='Assigner par'),
        ),
    ]
