# Generated by Django 4.2.16 on 2024-11-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0016_alter_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='marge_previsionnel',
            field=models.IntegerField(blank=True, null=True, verbose_name='marge previsionnel'),
        ),
        migrations.AddField(
            model_name='project',
            name='marge_previsionnel',
            field=models.IntegerField(blank=True, null=True, verbose_name='marge previsionnel'),
        ),
    ]
