# Generated by Django 4.2.16 on 2024-11-24 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracelan', '0017_historicalproject_marge_previsionnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name="Date de debut de l'événement")),
                ('end_date', models.DateTimeField(verbose_name="Date de fin de l'événement")),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(blank=True, choices=[('non_debute', 'non debuté'), ('en_cours', 'en cours'), ('Terminée', 'Completed'), ('en_attente', 'en attente')], default='not_started', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('non_debute', 'non debuté'), ('en_cours', 'en cours'), ('Terminée', 'Completed'), ('en_attente', 'en attente')], default='not_started', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name="Date de debut de l'événement")),
                ('end_date', models.DateTimeField(verbose_name="Date de fin de l'événement")),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_type', models.CharField(choices=[('producteur', 'Producteur'), ('cooperative', 'Coopérative'), ('ville', 'Ville'), ('district', 'District'), ('region', 'Région')], max_length=20, verbose_name="Type d'invité")),
                ('invite_id', models.IntegerField(verbose_name="ID de l'entité invitée")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tracelan.event')),
            ],
        ),
    ]
