# Generated by Django 4.2.16 on 2024-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0020_event_banner_historicalevent_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvite',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmation de présence'),
        ),
    ]
