# Generated by Django 4.2.16 on 2024-11-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0021_eventinvite_confirmation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparcelle',
            name='projet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracelan.project'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='projet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracelan.project'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracelan.project'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracelan.project'),
        ),
    ]
