# Generated by Django 4.2.16 on 2024-11-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0022_historicalparcelle_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducteur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
