# Generated by Django 4.2.16 on 2024-11-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0025_alter_cooperative_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureSeasonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_culture', models.CharField(max_length=100)),
                ('annee_mise_en_place', models.PositiveIntegerField()),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('dernier_rendement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pratiques_culturales', models.TextField(blank=True, null=True)),
                ('utilise_fertilisants', models.BooleanField(default=False)),
                ('type_fertilisants', models.TextField(blank=True, null=True)),
                ('analyse_sol', models.BooleanField(default=False)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures_seasonal', to='tracelan.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='CulturePerennial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_culture', models.CharField(max_length=100)),
                ('annee_mise_en_place', models.PositiveIntegerField()),
                ('date_derniere_recolte', models.DateField(blank=True, null=True)),
                ('dernier_rendement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pratiques_culturales', models.TextField(blank=True, null=True)),
                ('utilise_fertilisants', models.BooleanField(default=False)),
                ('type_fertilisants', models.TextField(blank=True, null=True)),
                ('analyse_sol', models.BooleanField(default=False)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures_perennial', to='tracelan.parcelle')),
            ],
        ),
    ]
