# Generated by Django 4.2.16 on 2024-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0027_historicalparcelle_affectations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparcelle',
            name='dimension_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='dimension_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
