# Generated by Django 4.2.16 on 2024-11-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracelan', '0028_alter_historicalparcelle_dimension_ha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=50, verbose_name='Type de Champ')),
                ('required', models.BooleanField(default=True, verbose_name='Requis')),
                ('options', models.TextField(blank=True, help_text="Valeurs séparées par des virgules pour 'select', 'checkbox', ou 'radio'.", null=True, verbose_name='Options')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Formulaire')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='tracelan.project', verbose_name='Projet')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tracelan.dynamicform')),
            ],
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracelan.dynamicfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='tracelan.formresponse')),
            ],
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tracelan.dynamicform', verbose_name='Formulaire'),
        ),
    ]
